KManager.action :bootstrap do
  def on_action
    application_name = :conventional_gitflow
    director = Dsl::RubyGemDsl
      .init(k_builder,
        template_base_folder: 'ruby/gem',
        on_exist:             :compare,     # %i[skip write compare]
        on_action:            :queue,      # %i[queue execute]
        repo_name:            application_name,
        application:          application_name
      )
      .github do
        parent.options.repo_info = repo_info
        # delete_repository # (name: :xmen, organization: 'klueless-webpack5-samples')
        # sleep 2; open_repository # (name: :xmen, organization: 'klueless-webpack5-samples')
        # create_repository # (name: :xmen, organization: 'klueless-webpack5-samples')
        # sleep 2; open_repository # (name: :xmen, organization: 'klueless-webpack5-samples')
        # list_repositories
      end
      .blueprint(
        name: :bin_hook,
        description: 'BIN/Hook structures') do

        cd(:app)

        dom = parent.options.to_h
          .merge(options.to_h)
          .merge(
            common_sh: template_content('bin/runonce/common.sh')
          )

        # debug
        # log.line
        # log.structure(dom)

        add('.gitignore')

        # add('hooks/pre-commit')         # NOT IMPLEMENTED
        # add('hooks/update-version')     # NOT IMPLEMENTED
    
        add('bin/setup', dom: dom)
        add('bin/console', dom: dom)
    
        run_command('git init')
        run_template_script('bin/runonce/git-setup.sh', dom: dom)
      end
      .blueprint(
        name: :baseline,
        description: 'Baseline files',
        on_exist: :write) do

        add('lib/conventional_gitflow.rb'         , template_file: 'lib/applet_name.rb'        ) #, after_write: 'prettier')
        add('lib/conventional_gitflow/version.rb' , template_file: 'lib/applet_name/version.rb') #, after_write: 'prettier')
        add('spec/conventional_gitflow_spec.rb'   , template_file: 'spec/applet_name_spec.rb'  )
    
        # add('spec/spec_helper.rb')
        
        # add('.rspec')
        # add('.rubocop.yml')
        # add('.travis.yml'                     , command: 'delete', note: 'this was generated by bundle gem')
        # add('applet_name.gemspec'             , 'conventional_gitflow.gemspec')
        # add('CODE_OF_CONDUCT.md')
        # add('Gemfile')
        # add('Guardfile')
        # add('LICENSE.txt')
        # add('Rakefile')
        # add('README.md')
      end
      .blueprint do
        # row '.github/workflows/main.yml'
      end

    # director.k_builder.debug
    director.play_actions
    # director.builder.logit
  end
end
