#!/usr/bin/env bash
echo 'xxxxxxxxxxxxxxxxxx'

if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert)(\(.+?\))?!?: .{1,}$"; then
    echo "Aborting commit. Please follow conventional commit message guidelines" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,200}$"; then
    echo "Aborting commit. Your commit message is too long." >&2
    exit 1
fi